"use client";
import ImageView from "../../Components/ImageView";
import { LuArrowUpRight } from "react-icons/lu";
import SeekingFund from "../../Components/SeekingFund";
import { useRouter } from "next/navigation";
import { nexaflowPageObj } from "../../utils/constants";
import nexaflowApi from "../../services/nexaflow";
import { useState, useEffect } from "react";
import { Loader } from "../../Components/Loader";
import Link from "next/link";
import Video from "../../Components/Video";
import Treasury from "../../Components/EarthTreasury";
import Nodes from "./Nodes";
import Features from "./Features";
import Projects from "./Projects";
import TradeDapp from "../../Components/Trade";
import buttonConfig from "../../utils/button";

const earth = "/assets/video/EarthVideo.mp4";
const earthHome = "/assets/images/earth-home.png";
const earthNode = "/assets/images/earthnode-home.png";
const groot = "/assets/images/faq.png";
const zap = "/assets/icons/zap.svg";
const check = "/assets/icons/Check_icon.svg";
const asset = "/assets/images/Climatesolutions.png";
const govern = "/assets/images/Communitygoverned.png";
const range = "/assets/images/Rangebound.png";
const pool = "/assets/images/Liquiditypool.png";
const highlight = "/assets/images/highlightText.png";
const graph = "/assets/icons/graph.svg";
const climateEnvironmentCrisis = "/assets/images/climate-environment.png";
const mainBottomSection = "/assets/images/main-bottom-section.png";

export default function Main() {
  const router = useRouter();
  const [partners, setPartners] = useState([]);
  const [updates, setUpdates] = useState([]);
  const [funding, setFunding] = useState([])

  useEffect(() => {
    const getPageByID = async () => {
      const page = await nexaflowApi.getPageByID({
        pageId: nexaflowPageObj.landingPage,
        websiteId: nexaflowPageObj.website,
      });
      setPartners(page?.Partners);
      setUpdates(page?.Updates);
      setFunding(page?.Stats);
    };

    getPageByID();
  }, []);
  // const funding = [
  //   {
  //     balance: "$17k+",
  //     impact: "Treasury",
  //   },
  //   {
  //     balance: "93",
  //     impact: "Holders",
  //   },
  //   {
  //     balance: "5",
  //     impact: "Projects Funded",
  //   },
  //   {
  //     balance: "25%",
  //     impact: "APY",
  //   },
  // ];
  const keys = [
    {
      title: "Mobilize",
      subTitle: "Capital",
      desc: "Incentivize and mobilize capital globally to allocate towards climate solutions.",
    },
    {
      title: "Value",
      subTitle: "Natural resources",
      desc: "Accurately value climate solutions and the positive externalities generated by them.",
    },
    {
      title: "Enable",
      subTitle: "Humanity",
      desc: "Use as a medium of exchange to build the solarpunk paradigm for the future.",
    },
  ];
  const services = [
    {
      title: `<p className="font-syne font-semibold text-[20px] text-center sm:text-left sm:text-[28px] text-[#EC8000]">
      Backed by Climate Solutions</p>`,
      description:
        "Each $EARTH is backed by a variety of on ground projects that are directly addressing the climate / environmental crisis while catering to humanities core needs",
      img: "/assets/images/asset.png",
    },
    {
      title: "Community Governed",
      description:
        "Monetary policy of $EARTH will be governed by Nodes of $EARTH with goal of achieving our mission/vision ",
      img: "/assets/images/community-governed.png",
    },
    {
      title: "Range Bound",
      description:
        "$EARTH is a new unit of value, not pegged to any currency. Designed to be loosely range bound, assets backing each token serve as the floor while valuing positive externalities created by those assets and the utility of the currency create a soft ceiling. ",
      img: "/assets/images/range.png",
    },
    {
      title: "Protocol Owned Liquidity",
      description:
        "Perpetual liquidity for you to swap your $EARTH for $DAI whenever you choose to irrespective of market conditions. This LP is owned by the treasury as a service to currency holders.",
      img: "/assets/images/pool.png",
    },
  ];
  const cardData = [
    {
      title: "What is $EARTH?",
      description: "Learn more about the digital currency",
      img: "/assets/images/Card1.png",
      link: "/resources",
    },
    {
      title: "How $EARTH works",
      description: "Read about the mechanics and flow of $EARTH",
      img: "/assets/images/Card2.png",
      link: "/works",
    },
    {
      title: "Buy $EARTH",
      description: "Trade on Uniswap",
      img: "/assets/images/Card3.png",
      link: "/earth",
    },
    {
      title: "Become an $EARTH Node.",
      description: "Learn about how to become a node",
      img: "/assets/images/Card4.png",
      link: "/community",
    },
  ];
  const features = [
    "Directly solving climate/environmental crisis",
    "Catering to our core needs",
    "Yield generating",
    "Building the solarpunk future",
  ];
  const social = [
    {
      image: "/assets/images/telegram.png",
      buttonLink: buttonConfig.social_home_telegram.link,
      external: buttonConfig.social_home_telegram.external,
    },
    {
      image: "/assets/images/twitter.png",
      buttonLink: buttonConfig.social_home_twitter.link,
      external: buttonConfig.social_home_twitter.external,
    },
    {
      image: "/assets/images/discord.png",
      buttonLink: buttonConfig.social_home_discord.link,
      external: buttonConfig.social_home_discord.external,
    },
    {
      image: "/assets/images/Mask.png",
      buttonLink: buttonConfig.social_home_farcaster.link,
      external: buttonConfig.social_home_farcaster.external,
    },
    {
      image: "/assets/images/cloud.png",
      buttonLink: buttonConfig.social_home_lens.link,
      external: buttonConfig.social_home_lens.external,
    },
    {
      image: "/assets/images/instagram.png",
      buttonLink: buttonConfig.social_home_instagram.link,
      external: buttonConfig.social_home_instagram.external,
    },
    {
      image: "/assets/images/linkedin.png",
      buttonLink: buttonConfig.social_home_linkedin.link,
      external: buttonConfig.social_home_linkedin.external,
    },
  ]
  const socialIcons = [
    {
      icon: "/assets/icons/notion.svg",
    },
    {
      icon: "/assets/icons/slack.svg",
    },
    {
      icon: "/assets/icons/google_drive.svg",
    },

    {
      icon: "/assets/icons/intercom.svg",
    },
    {
      icon: "/assets/icons/jira.svg",
    },
    {
      icon: "/assets/icons/dropbox.svg",
    },
    {
      icon: "/assets/icons/stripe.svg",
    },
    {
      icon: "/assets/icons/zapier.svg",
    },
    {
      icon: "/assets/icons/figma.svg",
    },
    {
      icon: "/assets/icons/confluence.svg",
    },
    {
      icon: "/assets/icons/mailchimp.svg",
    },
    {
      icon: "/assets/icons/zendesk.svg",
    },
    {
      icon: "/assets/icons/g-calendar.svg",
    },
    {
      icon: "/assets/icons/whatsapp.svg",
    },
    {
      icon: "/assets/icons/discord.svg",
    },
    {
      icon: "/assets/icons/bitbucket.svg",
    },
  ];
  // const updates = [
  //   {
  //     name: "Olivia Rhye • 20 Jan 2022",
  //     title: "UX review presentations",
  //     description:
  //       "How do you create compelling presentations that wow your colleagues and impress your managers?",
  //     img: "/assets/images/refi.png",
  //     link: true,
  //     tags: ["Design", "Research", "Presentation"],
  //   },
  //   {
  //     name: "Solarpunkmaxi • 19 Jan 2022",
  //     title: "What is solarpunk?",
  //     description:
  //       "Linear helps streamline software projects, sprints, tasks, and bug tracking. Here’s how to get...",
  //     img: "/assets/images/baker.png",
  //     tags: ["Design", "Research"],
  //   },
  //   {
  //     name: "TreegensDAO • 18 Jan 2022",
  //     title: "A new unit of value",
  //     description:
  //       "The rise of RESTful APIs has been met by a rise in tools for creating, testing, and manag...",
  //     img: "/assets/images/steiner.png",
  //     tags: ["Design", "Research"],
  //   },
  //   {
  //     name: "TreegensDAO • 18 Jan 2022",
  //     title: "Real world impact",
  //     description:
  //       "The rise of RESTful APIs has been met by a rise in tools for creating, testing, and manag...",
  //     img: "/assets/images/real-world.png",
  //     tags: ["Design", "Research"],
  //   },
  // ];
  return (
    <div className='mt-20'>
      {" "}
      <div className='relative h-[100vh] 2xl:h-[95vh] '>
        <ImageView
          src={earthHome}
          alt='earthcoin'
          width={500}
          height={500}
          className='object-cover w-full h-full'
        />
        {/* <Video
          src={earth}
          alt='earthcoin'
          className='object-cover w-full h-full'
        /> */}


        <div className='absolute md:top-[15rem] lg:top-[15rem] xl:top-[12rem]  text-[#000000] text-xl md:text-[40px] lg:text-[50px] xl:text-[60px] font-syne w-full text-center font-medium'>
          <p className="leading-none">
            Digital currency funding{" "}
            <br />
            regeneration
          </p>

          <button className='  text-white mt-5 xl:mt-10 font-inter font-semibold px-4 py-2 rounded-md bg-[#101323] border-[1px] border-[#EC8000] text-[16px]'>
            <Link
              href={buttonConfig?.home_get_earth?.link || ""}
              target={buttonConfig?.home_get_earth?.external ? "_blank" : "_self"}
            >
              {buttonConfig?.home_get_earth?.title}
            </Link>
          </button>

        </div>
      </div>


      <div className='mx-auto  pt-16 px-4 sm:px-[6%] mt-16 h-fit flex flex-col gap-12 items-center justify-center w-full'>
        <div className='flex flex-col items-center justify-center w-full pb-10 sm:flex-row'>
          {funding.map((impact, index) => (
            <div
              className={`flex flex-col px-2 py-4 sm:py-0 items-center  justify-center w-[16rem] ${index !== funding.length - 1
                ? " border-b-2 sm:border-b-0 sm:border-r-2 border-[#EAECF0]"
                : ""
                }`}
              key={index}
            >
              <p className='font-syne font-semibold text-[20px] text-center sm:text-[52px] text-[#EC8000]'>
                {impact.balance}
              </p>
              <p className='text-[#101828] text-center text-[16px]  font-medium font-inter'>
                {impact.title}
              </p>
            </div>
          ))}
        </div>

        <div>
          <p className="leading-10 text-[#000000] text-[20px] md:text-[25px] lg:text-[30px] xl:text-[35px] font-syne w-full text-center font-semibold">
            Just ONE transaction to get Rewarded for
            <br />
            <span className="text-[#EC8000]"> Climate Action</span>
          </p>
        </div>

        <ImageView
          src={earthNode}
          alt='earthcoin'
          width={500}
          height={500}
          className='object-cover w-full h-full'
        />

        {/* <div className="flex gap-x-[32px] py-[55px]">
          {keys.map((data) => (
            <div
              key={data.title}
              className="flex flex-col items-center border border-lightestGray pt-[40px] rounded-[16px] shadow-cardShadow"
            >
              <h1 className="text-[20px] font-inter font-semibold text-darkGray">
                {data.title}
              </h1>
              <h2 className="text-[16px] font-inter font-noemal text-lightGray">
                {data.subTitle}
              </h2>
              <p className="text-[18px] text-center p-[32px] font-inter font-noemal text-lightGray">
                {data.desc}
              </p>
            </div>
          ))}
        </div> */}
        <p className="text-[#000000] mt-5 text-[20px] md:text-[25px] lg:text-[30px] xl:text-[35px] font-syne w-full text-center font-semibold">
          What  is $EARTH?
        </p>
        <Features />

        {/* <Projects /> */}
        {/* <div className='flex flex-col gap-8 mt-3'>
          <div className='flex flex-col shadow gap-4 sm:flex-row p-5 items-center sm:items-start justify-between border-2 border-[#EAECF0] rounded-lg'>
            <div className='flex flex-col w-full sm:w-[60%] p-10 justify-center items-center sm:items-start '>
              <p className='font-syne font-semibold text-[20px] text-center sm:text-left sm:text-[28px] text-black'>
                Backed by{" "}
                <span className='text-[#EC8000]'> Climate Solutions</span>
              </p>
              <p className='text-[#475467]  text-center sm:text-left text-[16px] py-5 font-normal font-inter'>
                Each $EARTH is backed by a variety of on ground projects that
                are directly addressing the climate / environmental crisis while
                catering to humanities core needs
              </p>
            </div>
            <div className='p-5'>
              <ImageView
                src={asset}
                alt='service'
                width={600}
                height={300}
                className={` w-48 h-44 object-contain `}
              />
            </div>
          </div>
          <div className='flex flex-col shadow gap-4 sm:flex-row p-5 items-center sm:items-start justify-between border-2 border-[#EAECF0] rounded-lg'>
            <div className='flex flex-col w-full sm:w-[60%] justify-center p-10 items-center sm:items-start '>
              <p className='font-syne font-semibold text-[20px] text-center sm:text-left sm:text-[28px] text-[#EC8000]'>
                Community
                <span className='text-black'> Governed</span>
              </p>
              <p className='text-[#475467]  text-center sm:text-left text-[16px] py-5  font-normal font-inter'>
                Monetary policy of $EARTH will be governed by Nodes of $EARTH
                with goal of achieving our mission/vision
              </p>
            </div>
            <div className='p-5'>
              <ImageView
                src={govern}
                alt='service'
                width={600}
                height={300}
                className={` w-48 h-44 object-contain `}
              />
            </div>
          </div>
          <div className='flex flex-col shadow gap-4 sm:flex-row p-5 items-center sm:items-start justify-between border-2 border-[#EAECF0] rounded-lg'>
            <div className='flex flex-col w-full sm:w-[60%] justify-center p-10 items-center sm:items-start '>
              <p className='font-syne font-semibold text-[20px] text-center sm:text-left sm:text-[28px] text-[#EC8000]'>
                Range
                <span className='text-black'> Bound</span>
              </p>
              <p className='text-[#475467]  text-center sm:text-left text-[16px] py-5  font-normal font-inter'>
                $EARTH is a new unit of value, not pegged to any currency.
                Designed to be loosely range bound, assets backing each token
                serve as the floor while valuing positive externalities created
                by those assets and the utility of the currency create a soft
                ceiling.
              </p>
            </div>
            <div className='p-5'>
              <ImageView
                src={range}
                alt='service'
                width={600}
                height={300}
                className={` w-48 h-44 object-contain `}
              />
            </div>
          </div>
          <div className='flex flex-col shadow gap-4 sm:flex-row p-5 items-center sm:items-start justify-between border-2 border-[#EAECF0] rounded-lg'>
            <div className='flex flex-col w-full sm:w-[60%] justify-center p-10 items-center sm:items-start '>
              <p className='font-syne font-semibold text-[20px] text-center sm:text-left sm:text-[28px] text-black '>
                Protocol Owned
                <span className='text-[#EC8000]'> Liquidity</span>
              </p>
              <p className='text-[#475467]  text-center sm:text-left text-[16px] py-5  font-normal font-inter'>
                Perpetual liquidity for you to swap your $EARTH for $DAI
                whenever you choose to irrespective of market conditions. This
                LP is owned by the treasury as a service to currency holders.
              </p>
            </div>
            <div className='p-5'>
              <ImageView
                src={pool}
                alt='service'
                width={600}
                height={300}
                className={` w-48 h-44 object-contain `}
              />
            </div>
          </div>
        </div> */}
      </div>
      <div className=' relative mb-16 -mt-10 max-w-screen-2xl pt-16 mx-auto px-4 sm:px-[6%] '>
        <ImageView
          alt='social'
          src={mainBottomSection}
          width={1440}
          height={430}
          className='w-full rounded-lg h-[24rem] object-cover mt-20'
        />
        <div className='absolute top-[20rem] md:left-[8rem] lg:left-[14rem] xl:left-[22rem]  text-[#FFFFFF] md:text-[30px] lg:text-[34px] xl:text-[35px] font-syne text-center font-semibold'>
          <p>
            Crypto economics to value nature
          </p>
        </div>
      </div>
      <div>
        {/* <div className='max-w-screen-2xl pt-16 mx-auto px-4 sm:px-[6%]  h-fit flex flex-col gap-12 items-center justify-center w-full'>
          <div className='flex items-center flex-col w-[80%] px-20 mt-28 gap-4 '>
            <p className='text-[#EC8000] font-semibold text-center text-[14px] font-inter'>
              What is $EARTH
            </p>
            <p className='text-[#101828] font-semibold text-center text-[30px] sm:text-[40px] font-syne'>
              Borderless, capital efficient funnel mobilizing climate finance
            </p>
            <p className='text-[#475467] text-center font-normal   text-[16px] font-inter'>
              Giving the power to anyone, anywhere in the world to fund climate
              action via $EARTH
            </p>
          </div>
        </div>
        <ImageView
          src={climateEnvironmentCrisis}
          className='py-[30px] mt-8 w-full'
          alt='check'
          width={1440}
          height={2709}
        /> */}
      </div>
      {/* <Treasury /> */}
      <Nodes />
      <div className='max-w-screen-2xl pt-16 mx-auto px-4 sm:px-[6%]  h-fit flex flex-col gap-12 items-center justify-center w-full'>
        <div className='flex flex-col items-center gap-2'>
          <p className='text-[#EC8000] font-semibold text-center text-[14px] font-inter'>
            Partners
          </p>
          <p className='text-[#101828] font-semibold text-center text-[30px] sm:text-[40px] font-syne'>
            Agents of Change
          </p>
          <p className='text-[#475467] text-center font-normal  text-[16px] font-inter'>
            Projects collaborating with $EARTH to fulfil its mission/vision
          </p>
        </div>
        <div className='flex flex-wrap  sm:px-[32%] justify-center mt-6 gap-1 sm:gap-5'>
          {partners && partners?.length ? (
            partners.map((partner, index) => (
              <Link href={partner?.link} className='cursor-pointer' key={index}>
                <ImageView
                  alt='social'
                  src={partner.icon}
                  width={60}
                  height={60}
                />
              </Link>
            ))
          ) : (
            <div className='w-full h-[6rem]'>
              <Loader />
            </div>
          )}
        </div>
        {/* <button className='w-fit  text-white font-inter flex h-10 items-center justify-center rounded-md bg-[#EC8000] p-2 text-sm'>
        <Link
              href={buttonConfig?.home_partners?.link || ""}
              target={buttonConfig?.home_partners?.external ? "_blank" : "_self"}
            >
              {buttonConfig?.home_partners?.title}
            </Link>
        </button> */}
      </div>
      <div className=' relative max-w-screen-2xl pt-16 mx-auto px-4 sm:px-[6%] '>
        <ImageView
          alt='social'
          src={mainBottomSection}
          width={1440}
          height={430}
          className='w-full rounded-lg h-[24rem] object-cover mt-20'
        />
        <div className='absolute top-[16rem] md:left-[6rem] lg:left-[12rem] xl:left-[18rem]  text-[#FFFFFF] md:text-[30px] lg:text-[34px] xl:text-[35px] font-syne text-center font-semibold'>
          <p>
            We do not inherit this world from our parents <br />
            We borrow it from our children <br />
            Let&apos;s leave it better than we found it
          </p>
        </div>
      </div>
      <div className='max-w-screen-2xl pt-16 mx-auto px-4 sm:px-[6%]  h-fit flex flex-col gap-12 items-center justify-center w-full'>
        <div className='flex flex-col items-center gap-2'>
          <p className='text-[#EC8000] font-semibold text-center text-[14px] font-inter'>
            News
          </p>
          <p className='text-[#101828] font-semibold text-center text-[30px] sm:text-[40px] font-syne'>
            Latest updates
          </p>
          <p className='text-[#475467] text-center font-normal  text-[16px] font-inter'>
            Stay updated with the latest progress on $Earth
          </p>
        </div>
      </div>
      <div className='grid w-full grid-cols-1 px-20 mt-8 sm:grid-cols-2 gap-x-6 gap-y-5'>
        {updates && updates?.length
          ? updates.map((card, index) => (
            <div
              className={`flex cursor-pointer w-full items-start ${index === 0
                ? "col-span-1 sm:col-span-1 flex-col row-span-1 sm:row-span-3"
                : "col-span-1 flex-row sm:col-span-1"
                }`}
              key={index}
            >
              <ImageView
                src={card.image}
                alt={card.name}
                width={200}
                height={200}
                className={`${index === 0
                  ? "w-full h-[20rem] object-cover"
                  : "w-full h-40 sm:w-full object-cover"
                  }`}
              />
              <div
                className={`${index === 0 ? "mt-4" : "flex flex-col gap-2 px-4"
                  }`}
              >
                <p className='text-[#EC8000] font-inter font-semibold text-[12px]'>
                  {card?.name} • {card?.date}
                </p>
                <div className='flex items-start justify-between mt-2'>
                  <p
                    className={`text-[#101828] font-inter font-semibold text-[16px] ${index === 0 ? "font-syne text-[22px]" : ""
                      }`}
                  >
                    {card?.title}
                  </p>
                  {index === 0 ? (
                    <LuArrowUpRight size={22} color='#101828' />
                  ) : (
                    ""
                  )}
                </div>
                <p
                  className={`text-[#475467] ${index === 0 ? "mt-2" : ""
                    } font-inter w-[100%] font-normal text-[14px]`}
                >
                  {card?.description}
                </p>
                <div
                  className={`flex items-center ${index === 0 ? "mt-4" : "mt-0"
                    } gap-2`}
                >
                  {card && card?.length
                    ? card?.tags.map((tag, i) => (
                      <p
                        className={`rounded-full flex py-[2px] px-2 font-inter text-[12px] font-medium ${tag === "Design"
                          ? "text-[#EC8000] bg-[#FFFCF8]"
                          : tag === "Research"
                            ? "bg-[#EEF4FF] text-[#3538CD]"
                            : tag === "Presentation"
                              ? "bg-[#FDF2FA] text-[#C11574]"
                              : ""
                          }`}
                        key={i}
                      >
                        {tag}
                      </p>
                    ))
                    : null}
                </div>
              </div>
            </div>
          ))
          : null}

        {/* {social && social?.length ? (
            social.map((partner, index) => (
          
          <div
            className={`flex cursor-pointer w-full items-start ${
              index === 0
                ? "col-span-1 sm:col-span-1 flex-col row-span-1 sm:row-span-3"
                : "col-span-1 flex-row sm:col-span-1 "
            }`}
            key={index}
          >
            <ImageView
              src={card.image}
              alt={card.name}
              width={200}
              height={200}
              className={`${
                index === 0
                  ? "w-full h-[20rem] object-cover"
                  : "w-full h-40 sm:w-full object-cover"
              }`}
            />
            <div
              className={`${index === 0 ? "mt-4" : "flex flex-col gap-2 px-4"}`}
            >
              <p className='text-[#EC8000] font-inter font-semibold text-[12px]'>
                {card?.name}
              </p>
              <div className='flex items-start justify-between mt-2'>
                <p
                  className={`text-[#101828] font-inter font-semibold text-[16px] ${
                    index === 0 ? "font-syne text-[22px]" : ""
                  }`}
                >
                  {card?.title}
                </p>
                {card?.link && <LuArrowUpRight size={22} color='#101828' />}
              </div>
              <p
                className={`text-[#475467] ${
                  index === 0 ? "mt-2" : ""
                } font-inter w-[100%] font-normal text-[14px]`}
              >
                {card?.description}
              </p>
              <div
                className={`flex items-center ${
                  index === 0 ? "mt-4" : "mt-0"
                }  gap-2`}
              >
                {card?.tags.map((tag, i) => (
                  <p
                    className={`rounded-full flex py-[2px] px-2 font-inter text-[12px] font-medium ${
                      tag === "Design"
                        ? "text-[#EC8000] bg-[#FFFCF8]"
                        : tag === "Research"
                        ? "bg-[#EEF4FF] text-[#3538CD]"
                        : tag === "Presentation"
                        ? "bg-[#FDF2FA] text-[#C11574]"
                        : ""
                    }`}
                    key={i}
                  >
                    {tag}
                  </p>
                ))}
              </div>
            </div>
          </div>
        ))
      )
    } */}
      </div>
      <div className='grid items-center justify-center sm:px-[6%] w-full grid-cols-1 gap-8 px-4 mx-auto mt-28 sm:grid-cols-2'>
        {cardData?.map((data, index) => (
          <div
            className='relative w-full cursor-pointer grow'
            key={index}
            onClick={() => router.push(data?.link)}
          >
            <ImageView
              src={data?.img}
              alt='main'
              width={600}
              height={600}
              className='rounded-xl w-full h-[14rem]  object-cover'
            />
            <Link
              href={data.link}
              className='flex flex-col w-full absolute p-[2rem] pb-[4rem] sm:p-[3rem] top-[0rem]'
            >
              <div className='flex items-center justify-between'>
                <p
                  className={`text-white  font-syne font-semibold text-[26px]`}
                >
                  {data?.title}
                </p>
                <LuArrowUpRight size={22} color='#fff' />
              </div>
              <p className='text-white font-inter mt-2  font-normal text-[16px]'>
                {data?.description}
              </p>
            </Link>
          </div>
        ))}
      </div>
      <div className='max-w-screen-2xl pt-16 mx-auto px-4 sm:px-[6%]  h-fit flex flex-col gap-12 items-center justify-center w-full'>
        <div className='flex flex-wrap justify-center gap-1 mt-6 sm:gap-4'>
          {social.map((partner, index) => (
            <Link
              key={index}
              href={partner?.buttonLink}
              target={partner?.external ? "_blank" : "_self"}
            >
              <ImageView
                alt='social'
                src={partner.image}
                width={40}
                height={40}
                className='w-full h-14 '
              />
            </Link>
            //    <a
            //    href={partner?.buttonLink}
            //    target='_blank'
            //    className='cursor-pointer'
            //    key={index}
            //  >
            //    <ImageView
            //      alt='social'
            //      src={partner.image}
            //      width={40}
            //      height={40}
            //      className='w-full h-14 '
            //    />
            //  </a>



          ))
          }
        </div>

        <p className='text-3xl font-medium font-syne '>Join us!</p>

        {/* <button className='w-fit  text-white font-inter flex h-10 items-center justify-center rounded-md bg-[#EC8000] p-2 text-sm'>
          View Partners
        </button> */}
      </div>
      <div className=' pt-0 mx-auto px-4 sm:px-[6%]  h-fit flex flex-col gap-12 items-center justify-center w-full'>
        <div className='relative w-full mt-0 sm:mt-28 sm:mb-8'>
          <ImageView
            src={groot}
            alt='groot'
            width={1216}
            height={300}
            className='w-full h-[350px] rounded-lg object-cover'
          />
          <div className='flex flex-col w-full justify-end items-center p-4 absolute bottom-[1.5rem]'>
            <p className='text-white font-inter text-center mt-3 font-medium text-[18px]'>
              Still have questions?
            </p>
            <p className='text-white font-inter text-center mt-1 font-light text-[16px]'>
              Can’t find the answer you’re looking for? Please drop a message to
              our team.
            </p>
            <button className='w-[100px] mt-4 text-white font-inter flex h-10 items-center justify-center rounded-md bg-[#EC8000] p-2 cursor-pointer text-sm'>
              <Link
                href={buttonConfig?.home_footer_banner?.link || ""}
                target={buttonConfig?.home_footer_banner?.external ? "_blank" : "_self"}
              >
                {buttonConfig?.home_footer_banner?.title}
              </Link>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
