import ImageView from "../../Components/ImageView";
import Card from "./Card";
import Community from "../../Components/Community";
const tokenomics = "/assets/images/tokenomics.png";
const curious = "/assets/images/Curious.png";
const protocol = "/assets/images/protocol.png";
const treasury1 = "/assets/images/treasury1.gif";
const treasury2 = "/assets/images/treasury2.gif";
const treasury3 = "/assets/images/treasury3.gif";
const treasury = "/assets/images/treasury.png";
const harvest = "/assets/images/harvest-treasury.png";

export default function Mechanics() {
  const data = [
    {
      title: "Mobilize",
      subtitle: "Capital",
      description:
        "Incentivize and mobilize capital globally to allocate towards climate solutions.",
    },
    {
      title: "Value",
      subtitle: "Natural resources",
      description:
        "Accurately value climate solutions and the positive externalities generated by them.",
    },
    {
      title: "Enable",
      subtitle: "Humanity",
      description:
        "Use as a medium of exchange to build the solarpunk paradigm for the future.",
    },
  ];

  const chartData = [
    {
      title: "Liquidity Pool",
      percent: "15.15%",
    },
    {
      title: "Partnerships / Rewards / IV",
      percent: "14.14%",
    },
    {
      title: "APY for Stakers",
      percent: "40.40%",
    },
    {
      title: "DAO",
      percent: "10.10%",
    },
  ];

  return (
    <div>
      <div className="mt-32 w-full max-w-screen-2xl mx-auto px-4 sm:px-[6%] flex gap-10 flex-col items-center pb-10">
        <div className="flex flex-col gap-2 items-center">
          <p className="text-[#EC8000] font-semibold text-center text-[14px] font-inter">
            About
          </p>
          <p className="text-[#101828] font-semibold text-center text-[30px] sm:text-[40px] font-syne">
            TOKENOMICS
          </p>
          <p className="text-[#475467] text-center font-normal  text-[16px] font-inter">
          The economic models behind $Earth funding climate solutions and putting Eco in Economy
          </p>
        </div>
        <ImageView
          src={tokenomics}
          alt="tokenomics"
          width={400}
          height={400}
          className="w-full mt-4 object-cover"
        />
        <div className="sm:px-[13%] px-4 flex flex-col w-full items-start">
          <p className="text-[#101828] font-semibold text-left mt-6 text-[20px] sm:text-[28px]  font-syne">
          $EARTH is designed to -
          </p>
           </div>
       
       
        <div className="grid gap-4 grid-cols-1 sm:grid-cols-3 mt-6">
          {data.map((option, index) => (
            <Card key={index} option={option} />
          ))}
        </div>
        <div className="sm:px-[13%] px-4 flex flex-col w-full items-start">
          <p className="text-[#101828] font-semibold text-left mt-6 text-[20px] sm:text-[28px]  font-syne">
            Here we look at how tokenomics have been designed to achieve these
            objectives
          </p>
          <div className="mt-6">
            <p className="text-[#475467] text-center sm:text-left font-normal  text-[16px] font-inter">
              In order to get an understanding of $EARTH currency design we will
              first explain key concepts and then take you through an example of
              how these concepts play out in action
            </p>
          </div>
          <div className="mt-6 w-full flex flex-col justify-between sm:flex-row gap-10 items-start sm:items-center border-b-2 pb-8 border-[#EAECF0] space-between">
            <p className="text-[#101828] w-[20%] font-semibold text-left   text-[20px]  font-syne">
              $Earth token -
            </p>

            <p className="text-[#475467] text-center sm:text-left font-normal w-[80%] text-[16px] font-inter">
              Token that can be minted/created only when petro $$$ are purged at
              the protocol level by Earth Nodes.
            </p>
          </div>
          <div className="mt-6 w-full flex flex-col sm:flex-row gap-10 items-start sm:items-center border-b-2 pb-8 border-[#EAECF0] space-between">
            <p className="text-[#101828] w-[20%] font-semibold text-left   text-[20px]  font-syne">
              Neoliberal Value -
            </p>
            <div className="flex flex-col gap-5 w-[80%] items-start">
              <p className="text-[#475467] text-center sm:text-left font-normal  text-[16px] font-inter">
                Price of real world assets backing each $EARTH in the existing
                neoliberal paradigm. Value of this cannot go down,
                <span className="tex-[#EC8000] font-semibold"> EVER!</span> This
                is coded into the smart contracts.
              </p>
              <p className="text-[#101828] font-semibold text-left   text-[18px]  font-syne">
                Treasury value in $ ÷ $EARTH in circulation
              </p>
            </div>
          </div>
          <div className="mt-6 w-full flex flex-col justify-between sm:flex-row gap-10 items-start sm:items-center border-b-2 pb-8 border-[#EAECF0] space-between">
            <p className="text-[#101828] w-[20%] font-semibold text-left   text-[20px]  font-syne">
              Mint Multiple -
            </p>

            <p className="text-[#475467] text-center sm:text-left font-normal w-[80%]  text-[16px] font-inter">
              The premium Earth Nodes pay to mint $EARTH on the neoliberal value
              of assets in the treasury
            </p>
          </div>
          <div className="mt-6 w-full flex flex-col justify-between sm:flex-row gap-10 items-start sm:items-center border-b-2 pb-8 border-[#EAECF0] space-between">
            <p className="text-[#101828] w-[20%] font-semibold text-left   text-[20px]  font-syne">
              Harvest -
            </p>

            <p className="text-[#475467] text-center sm:text-left font-normal w-[80%]  text-[16px] font-inter">
              Function that lets the protocol mint $EARTH to the extent that it
              doesn&apos;t dilute the neoliberal value of assets backing each
              $EARTH
            </p>
          </div>
          <div className="mt-6 w-full flex flex-col justify-between sm:flex-row gap-10 items-start sm:items-center border-b-2 pb-8 border-[#EAECF0] space-between">
            <p className="text-[#101828] w-[20%] font-semibold text-left   text-[20px]  font-syne">
              Mint price -
            </p>

            <p className="text-[#101828] font-semibold text-left  w-[80%] text-[18px]  font-syne">
              Neoliberal value of assets backing each $EARTH x Mint multiple
            </p>
          </div>
          <p className="text-[#101828] font-semibold text-left mt-6 text-[20px] sm:text-[28px] mr-10 font-syne">
            Example
          </p>
          <div className="mt-6">
            <p className="text-[#475467] text-center sm:text-left font-normal  text-[16px] font-inter">
              Let&apos;s consider Jimi, who has become an
              <span className="text-[#EC8000] font-semibold">$EARTH Node</span>.
              He decides to purge $100,000 when the price of $EARTH at the
              protocol level is $10.
              <br />
              1. In this scenario, Jimi{" "}
              <span className="text-[#EC8000] font-semibold">purges</span>{" "}
              $100,000 for 10,000 $EARTH tokens from the protocol.
            </p>
          </div>
          <ImageView
            src={treasury1}
            alt="graph"
            width={400}
            height={400}
            className="w-full mt-4 object-cover"
          />
          <p className="text-[#475467] text-center sm:text-left font-normal  text-[16px] font-inter">
            Breakdown of Events:
            <br />
            <br />
            a. $EARTH is minted because dollars have been purged directly at the
            protocol level.
            <br />
            <br />
            b. Jimi pays a price for $EARTH ($10) derived from the formula:
          </p>
          <p className="text-[#101828] font-semibold text-left mt-6 text-[20px] sm:text-[20px] mr-10 font-syne">
            Neoliberal Value of assets backing each $EARTH today ( $5 ) x Mint
            Multiple (2) = $10
          </p>
          <div className="mt-6">
            <p className="text-[#475467] text-center sm:text-left font-normal  text-[16px] font-inter">
              2. By paying a premium over the neoliberal value of assets in the
              treasury, Jimi{" "}
              <span className="text-[#EC8000] font-semibold">
                {" "}
                values the positive externalities{" "}
              </span>{" "}
              or ecosystem services generated by the assets in the treasury
              proactively, rather than waiting for the free market to price the
              value of healthy soil, thriving biodiversity, clean air and water,
              a stable carbon cycle, habitable environments, nutrient-dense
              food, well-being, etc.
            </p>
            <p className="text-[#101828] font-semibold text-left mt-6 text-[20px] sm:text-[20px] mr-10 font-syne">
              When Jimi pays this premium proactively, it funnels more capital
              into projects that generate these positive externalities.
            </p>
            <p className="text-[#475467] text-center sm:text-left font-normal mt-2 text-[16px] font-inter">
              3. So, with the additional 10,000 $EARTH minted via the Harvest
              function, we now have 20,000 $EARTH in circulation (10,000 with
              Jimi and 10,000 with the Harvest Treasury).
            </p>
            <br />
          </div>
          <div className="mt-6 w-full flex flex-col justify-between sm:flex-row gap-10 items-start sm:items-center border-b-2 pb-8 border-[#EAECF0] space-between">
            <p className="text-[#101828] w-[30%] font-semibold   text-left   text-[20px]  font-syne">
              Treasury -
            </p>
            <p className="text-[#101828] font-semibold text-left w-[50%]   text-[18px]  font-syne">
              $100,000
            </p>
          </div>
          <div className="mt-6 w-full flex justify-between flex-col sm:flex-row gap-10 items-start sm:items-center border-b-2 pb-8 border-[#EAECF0] space-between">
            <p className="text-[#101828] w-[30%] font-semibold text-left   text-[20px]  font-syne">
              Total $EARTH in circulation -
            </p>
            <p className="text-[#101828] font-semibold text-left w-[50%]  text-[18px]  font-syne">
              20,000 $EARTH
            </p>
          </div>
          <div className="mt-6 w-full flex flex-col justify-between sm:flex-row gap-10 items-start sm:items-center border-b-2 pb-8 border-[#EAECF0] space-between">
            <p className="text-[#101828] w-[30%] font-semibold text-left   text-[20px]  font-syne">
              Neoliberal value of assets backing each $EARTH -
            </p>
            <p className="text-[#101828] font-semibold text-left w-[50%]   text-[18px]  font-syne">
              $100,000 ÷ 20,000 = $5
            </p>
          </div>
          <p className="text-[#475467] text-center mt-6 sm:text-left font-normal  text-[16px] font-inter">
            The protocol ensures that minting $EARTH does not dilute the
            neoliberal value of assets backing each $EARTH.
            <br />
            <br />
            Once the funds purged by Jimi are transferred to the treasury, they
            are allocated to projects chosen by $EARTH holders. These projects
            then serve as assets backing each $EARTH in circulation.
          </p>
          <ul className="list-disc pl-4">
            <li className="text-[#475467] text-center mt-6 sm:text-left font-normal  text-[16px] font-inter">
              80% of the treasury funds are allocated to projects.
            </li>
            <li className="text-[#475467] text-center  sm:text-left font-normal  text-[16px] font-inter">
              20% goes to the $EARTH/$DAI Liquidity Pool, owned by the protocol,
              to ensure $EARTH holders can exit whenever they choose.
            </li>
          </ul>
          <ImageView
            src={treasury2}
            alt="treasury"
            width={400}
            height={400}
            className="w-full mt-4 object-cover"
          />
          <p className="text-[#101828] font-semibold text-left mt-6 text-[20px] sm:text-[28px] mr-10 font-syne">
            $Earth Harvest
          </p>
          <div className="mt-6">
            <p className="text-[#475467] text-center sm:text-left font-normal  text-[16px] font-inter">
              Once the protocol invokes the Harvest function and 10,000 $EARTH
              are transferred to the Harvest Treasury, this $EARTH is allocated
              as follows:
            </p>
            <ul className="list-disc pl-4">
              <li className="text-[#475467] text-center mt-6 sm:text-left font-normal  text-[16px] font-inter">
                Staking: $EARTH is used to provide an APY to stakers, currently
                at 25%.
              </li>
              <li className="text-[#475467] text-center  sm:text-left font-normal  text-[16px] font-inter">
                Liquidity Pool: $EARTH, combined with the 20% allocation of
                $DAI, is used to build the $EARTH/$DAI Liquidity Pool for
                holders.
              </li>
              <li className="text-[#475467] text-center  sm:text-left font-normal  text-[16px] font-inter">
                Community: $EARTH to reward proactive community members.
              </li>
              <li className="text-[#475467] text-center  sm:text-left font-normal  text-[16px] font-inter">
                Solarpunk DAO: Compensation for the work done by Solarpunk DAO
                to run $EARTH.
              </li>
            </ul>
            <ImageView
              src={treasury3}
              alt="harvest"
              width={400}
              height={400}
              className="w-full mt-4 object-cover"
            />
          </div>
        </div>
        <div className="w-full h-[1.5px] my-8 bg-[#F2F4F7]"></div>

        <Community
          title="Still curious?"
          img={curious}
          description="Join our social community to understand further!"
        />
      </div>
    </div>
  );
}
