import ImageView from "../../Components/ImageView";
import Card from "./Card";
import { useState, useEffect } from "react";
import Community from "../../Components/Community";
const tokenomics = "/assets/images/tokenomics.png";
const intrinsicGraph = "/assets/images/intrinsic-Graph.png";
const pieChart = "/assets/images/Pie chart.png";
export default function Mechanics() {
  const data = [
    {
      title: "Mobilize",
      subtitle: "Capital",
      description:
        "Incentivize and mobilize capital globally to allocate towards climate solutions.",
    },
    {
      title: "Value",
      subtitle: "Natural resources",
      description:
        "Accurately value climate solutions and the positive externalities generated by them.",
    },
    {
      title: "Enable",
      subtitle: "Humanity",
      description:
        "Use as a medium of exchange to build the solarpunk paradigm for the future.",
    },
  ];
  const Editordata = [
    {
      details:
        '<p><span style="color: rgb(32,33,36);background-color: rgb(255,255,255);font-size: 17px;font-family: inter; font-weight:400;">Helios is an open-source platform enabling both web3 &amp; traditional investment in profitable, high impact solar projects in emerging markets, earning users stable, double digit yields uncorrelated with crypto or public markets while averting millions of tonnes of CO2 emissions each year. </span><span style="font-size: 17px;font-family: inter; font-weight:400;"><br><br></span><span style="color: rgb(32,33,36);background-color: rgb(255,255,255);font-size: 17px;font-family: inter; font-weight:400;">With a portfolio of solar assets across 4 continents, Helios is perpetually deploying capital &amp; seeking new C&amp;I solar investment opportunities (50-500kW) globally.</span><span style="font-size: 17px;font-family: inter; font-weight:400;"><br><br></span><span style="color: rgb(32,33,36);background-color: rgb(255,255,255);font-size: 17px;font-family: inter; font-weight:400;">Our project is entirely open source; no Helios employees take any salary; we aim to reinvest all earnings back into solar to create compounding impact.</span><span style="font-size: 17px;font-family: inter; font-weight:400;"> </span></p>\n',
    },
  ];
  const chartData = [
    {
      title: "Liquidity Pool",
      percent: "15.15%",
    },
    {
      title: "Partnerships / Rewards / IV",
      percent: "14.14%",
    },
    {
      title: "APY for Stakers",
      percent: "40.40%",
    },
    {
      title: "DAO",
      percent: "10.10%",
    },
  ];
  const [editorLoaded, setEditorLoaded] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setEditorLoaded(true);
    }
  }, []);

  if (!editorLoaded) {
    return null;
  }

  const { Editor } = require("react-draft-wysiwyg");
  const { EditorState, ContentState } = require("draft-js");
  const htmlToDraft = require("html-to-draftjs").default;

  const addElement = (value) => {
    const contentBlock = htmlToDraft(value);
    const contentState = ContentState.createFromBlockArray(
      contentBlock.contentBlocks
    );
    const editorState = EditorState.createWithContent(contentState);
    return editorState;
  };
  return (
    <div>
      <div className="mt-32 w-full max-w-screen-2xl mx-auto px-4 sm:px-[6%] flex gap-10 flex-col items-center pb-10">
        <div className="flex flex-col gap-2 items-center">
          <p className="text-[#EC8000] font-semibold text-center text-[14px] font-inter">
            About
          </p>
          <p className="text-[#101828] font-semibold text-center text-[30px] sm:text-[40px] font-syne">
            TOKENOMICS
          </p>
          <p className="text-[#475467] text-center font-normal  text-[16px] font-inter">
            The economic models behind $Earth driving our solarpunk vision home
          </p>
        </div>
        <ImageView
          src={tokenomics}
          alt="tokenomics"
          width={400}
          height={400}
          className="w-full mt-4 object-cover"
        />
        <p className="text-[#101828] font-semibold text-center text-[20px] sm:text-[28px] mr-10 font-syne">
          $Earth has been created to -
        </p>
        <div className="grid gap-4 grid-cols-1 sm:grid-cols-3 mt-6">
          {data.map((option, index) => (
            <Card key={index} option={option} />
          ))}
        </div>
        <div className="sm:px-[23%] px-4 flex flex-col w-full items-start">
          <p className="text-[#101828] font-semibold text-left mt-6 text-[20px] sm:text-[28px] mr-10 font-syne">
            Keeping this in mind, tokenomics for $Earth have been designed such
            that -
          </p>
          <div className="mt-6">
            <Editor
              toolbarHidden
              editorState={addElement(Editordata[0]?.details)}
              wrapperClassName="demo-wrapper"
              editorClassName="richText-display"
              readOnly
            />
          </div>
          <p className="text-[#101828] font-semibold text-left mt-6  text-[20px] sm:text-[28px] mr-10 font-syne">
            $Earth token -
          </p>
          <div className="mt-6">
            <Editor
              toolbarHidden
              editorState={addElement(Editordata[0]?.details)}
              wrapperClassName="demo-wrapper"
              editorClassName="richText-display"
              readOnly
            />
          </div>
          <p className="text-[#101828] font-semibold text-left mt-6 text-[20px] sm:text-[28px] mr-10 font-syne">
            Intrinsic Value (IV)
          </p>
          <div className="mt-6">
            <Editor
              toolbarHidden
              editorState={addElement(Editordata[0]?.details)}
              wrapperClassName="demo-wrapper"
              editorClassName="richText-display"
              readOnly
            />
          </div>
          <ImageView
            src={intrinsicGraph}
            alt="graph"
            width={400}
            height={400}
            className="w-full mt-4 object-cover"
          />
          <p className="text-[#101828] font-semibold text-left mt-6 text-[20px] sm:text-[28px] mr-10 font-syne">
            $Earth Premium
          </p>
          <div className="mt-6">
            <Editor
              toolbarHidden
              editorState={addElement(Editordata[0]?.details)}
              wrapperClassName="demo-wrapper"
              editorClassName="richText-display"
              readOnly
            />
          </div>
          <p className="text-[#101828] font-semibold text-left mt-6 text-[20px] sm:text-[28px] mr-10 font-syne">
            $Earth Harvest
          </p>
          <div className="mt-6">
            <Editor
              toolbarHidden
              editorState={addElement(Editordata[0]?.details)}
              wrapperClassName="demo-wrapper"
              editorClassName="richText-display"
              readOnly
            />
          </div>
          <p className="text-[#101828] font-semibold text-left mt-6 text-[20px]  font-syne">
            All $Earth harvested through this will be utilized for the following
            -
          </p>
          <div className="flex flex-col gap-16 mt-3 w-full items-center justify-between sm:flex-row">
            <ImageView
              src={pieChart}
              alt="piechart"
              width={250}
              height={250}
              className="mt-4 object-cover"
            />
            <div className="flex gap-2 w-full grow flex-col">
              {chartData?.map((chart, index) => (
                <div
                  className="flex justify-between grow w-full gap-8 relative items-start"
                  key={index}
                >
                  <div
                    className={`${
                      chart.title === "Liquidity Pool"
                        ? "bg-[#F4AB1F]"
                        : chart.title === "Partnerships / Rewards / IV"
                        ? "bg-[#B2BC45]"
                        : chart.title === "APY for Stakers"
                        ? "bg-[#486D2F]"
                        : chart.title === "DAO"
                        ? "bg-[#EC8000]"
                        : ""
                    }w-[5px]  -left-3 top-[8px] absolute h-[5px] rounded-full`}
                  ></div>
                  <p className="text-[#475467] font-inter text-[14px] font-normal">
                    {chart?.title}
                  </p>
                  <p className="text-[#475467] font-inter text-[14px] font-normal">
                    {chart?.percent}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>

        <Community
          title="Still curious?"
          description="Join our social community to understand further!"
        />
      </div>
    </div>
  );
}
