import ImageView from "../../Components/ImageView";
import Card from "./Card";
const tokenomics = "/assets/images/tokenomics.png";
export default function Mechanics() {
  const data = [
    {
      title: "Mobilize",
      subtitle: "Capital",
      description:
        "Incentivize and mobilize capital globally to allocate towards climate solutions.",
    },
    {
      title: "Value",
      subtitle: "Natural resources",
      description:
        "Accurately value climate solutions and the positive externalities generated by them.",
    },
    {
      title: "Enable",
      subtitle: "Humanity",
      description:
        "Use as a medium of exchange to build the solarpunk paradigm for the future.",
    },
  ];
  return (
    <div>
      <div className="mt-32 w-full max-w-screen-2xl mx-auto px-4 sm:px-[6%] flex gap-10 flex-col items-center">
        <div className="flex flex-col gap-2 items-center">
          <p className="text-[#EC8000] font-semibold text-center text-[16px] font-inter">
            About
          </p>
          <p className="text-[#101828] font-semibold text-center text-[30px] sm:text-[48px] font-syne">
            TOKENOMICS
          </p>
          <p className="text-[#475467] text-center font-normal  text-[16px] font-inter">
            The economic models behind $Earth driving our solarpunk vision home
          </p>
        </div>
        <ImageView
          src={tokenomics}
          alt="tokenomics"
          width={400}
          height={400}
          className="w-full mt-4 object-cover"
        />
        <p className="text-[#101828] font-semibold text-center text-[20px] sm:text-[30px] mr-10 font-syne">
          $Earth has been created to -
        </p>
        <div className="grid gap-4 grid-cols-1 sm:grid-cols-3 mt-6">
          {data.map((option, index) => (
            <Card key={index} option={option} />
          ))}
        </div>
      </div>
    </div>
  );
}
