export default {
  home_get_earth: {
    title: "GET $EARTH",
    position: "Nodes",
    page: "/",
    external: false,
    link: "/dapp",
  },
  home_earthNode_learnMore: {
    title: "Learn more",
    position: "Nodes",
    page: "/",
    external: true,
    link: "",
  },
  home_earthNode_becomeNode: {
    title: "Become a NODE",
    position: "Nodes",
    page: "/",
    external: true,
    link: "",
  },
  home_partners: {
    title: "View Partners",
    position: "Partners",
    page: "/",
    external: true,
    link: "",
  },
  home_footer_banner: {
    title: "$Earth GPT",
    position: "AI Banner",
    page: "/",
    external: true,
    link: "",
  },
  social_home_telegram: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "",
  },
  social_home_twitter: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "",
  },
  social_home_discord: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "",
  },
  social_home_mask: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "",
  },
  social_home_cloud: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "",
  },
  social_home_instagram: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "",
  },
  social_home_linkedin: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "",
  },
  earth_protocol_becomenode: {
    title: "Become a NODE",
    position: "Nodes",
    page: "/earth",
    external: true,
    link: "",
  },
  earth_protocol_dapp: {
    title: "Go to DAPP",
    position: "Nodes",
    page: "/earth",
    external: true,
    link: "",
  },
  earth_uniswap_becomeNode: {
    title: "Go to Uniswap",
    position: "Nodes",
    page: "/earth",
    external: true,
    link: "https://app.uniswap.org/swap?inputCurrency=0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063&outputCurrency=0x9F9f149a02Cddc9a8251207cefD3fF774DAF56F6",
  },
  earth_footer_banner: {
    title: "Learn More",
    position: "Banner",
    page: "/earth",
    external: true,
    link: "",
  },
  faq_footer_banner: {
    title: "Earth GPT",
    position: "AI Banner",
    page: "/faq",
    external: true,
    link: "",
  },
  projects_footer_banner: {
    title: "Earth GPT",
    position: "AI Banner",
    page: "/projects",
    external: true,
    link: "",
  },
  network_community_bookslot: {
    title: "Book a slot",
    position: "Stepper",
    page: "/community",
    external: true,
    link: "",
  },
  network_community_verified: {
    title: "Get KYC verified",
    position: "Stepper",
    page: "/community",
    external: true,
    link: "",
  },
  network_community_dapp: {
    title: "Go to DAPP",
    position: "Stepper",
    page: "/community",
    external: true,
    link: "",
  },
  node_earth_mycelium_footer_banner: {
    title: "Learn More",
    position: "AI Banner",
    page: "/node",
    external: true,
    link: "",
  },
  media_get_started: {
    title: "Get started",
    position: "Startups",
    page: "/media",
    external: true,
    link: "",
  },
  dashboard_footer_banner: {
    title: "Learn More",
    position: "AI Banner",
    page: "/dashboard",
    external: true,
    link: "",
  },
};
