export default {
  home_get_earth: {
    title: "GET $EARTH",
    position: "Nodes",
    page: "/",
    external: false,
    link: "/dapp",
  },
  home_earthNode_learnMore: {
    title: "Learn more",
    position: "Nodes",
    page: "/",
    external: false,
    link: "/network",
  },
  home_earthNode_becomeNode: {
    title: "Become a NODE",
    position: "Nodes",
    page: "/",
    external: false,
    link: "/earthnode",
  },

  home_footer_banner: {
    title: "$Earth GPT",
    position: "AI Banner",
    page: "/",
    external: true,
    link: "https://chatgpt.com/g/g-dhkZ0P5ZL-ask-earth",
  },
  social_home_telegram: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "https://t.me/+MWUrdlbcUbE4MzA1",
  },
  social_home_twitter: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "https://twitter.com/solarpunkdao",
  },
  social_home_discord: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "https://discord.gg/67sjSmjd4m",
  },
  social_home_lens: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "",
  },
  social_home_farcaster: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "",
  },
  social_home_instagram: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "https://www.instagram.com/solarpunkdao.earth/",
  },
  social_home_linkedin: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "https://www.linkedin.com/company/earth-solarpunkdao/",
  },
  earth_protocol_becomenode: {
    title: "Become a NODE",
    position: "Nodes",
    page: "/earth",
    external: false,
    link: "/earthnode",
  },
  earth_protocol_dapp: {
    title: "Go to DAPP",
    position: "Nodes",
    page: "/earth",
    external: false,
    link: "/dapp",
  },
  earth_uniswap_becomeNode: {
    title: "Go to Uniswap",
    position: "Nodes",
    page: "/earth",
    external: true,
    link: "https://app.uniswap.org/swap?inputCurrency=0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063&outputCurrency=0x9F9f149a02Cddc9a8251207cefD3fF774DAF56F6",
  },
  footer_banner: {
    title: "Learn More",
    position: "Banner",
    page: "/",
    external: false,
    link: "",
  },
  faq_footer_banner: {
    title: "Earth GPT",
    position: "AI Banner",
    page: "/faq",
    external: true,
    link: "https://chatgpt.com/g/g-dhkZ0P5ZL-ask-earth",
  },
  projects_footer_banner: {
    title: "Earth GPT",
    position: "AI Banner",
    page: "/projects",
    external: true,
    link: "https://chatgpt.com/g/g-dhkZ0P5ZL-ask-earth",
  },
  network_earthnode_bookslot: {
    title: "Book a slot",
    position: "Stepper",
    page: "/earthnode",
    external: true,
    link: "https://calendly.com/earthcoin",
  },
  network_earthnode_verified: {
    title: "Get KYC verified",
    position: "Stepper",
    page: "/earthnode",
    external: false,
    link: "",
  },
  network_earthnode_googleForm: {
    title: "Google Form",
    position: "Stepper",
    page: "/earthnode",
    external: true,
    link: "https://forms.gle/zx6Si4FTMKNUpBzH6",
  },
  network_earthnode_dapp: {
    title: "Go to DAPP",
    position: "Stepper",
    page: "/earthnode",
    external: false,
    link: "",
  },
  media_get_started: {
    title: "Get $Earth",
    position: "Startups",
    page: "/media",
    external: false,
    link: "/dapp",
  },
};
