export default {
  home_get_earth: {
    title: "GET $EARTH",
    position: "Nodes",
    page: "/",
    external: false,
    link: "/dapp",
  },
  home_earthNode_learnMore: {
    title: "Learn more",
    position: "Nodes",
    page: "/",
    external: false,
    link: "/network",
  },
  home_earthNode_becomeNode: {
    title: "Become a NODE",
    position: "Nodes",
    page: "/",
    external: false,
    link: "/earthnode",
  },
  dapp_footer_banner: {
    title: "Get $Earth",
    position: "AI Banner",
    page: "/",
    external: false,
    link: "/dapp",
  },
  home_footer_banner: {
    title: "Ask $Earth",
    position: "AI Banner",
    page: "/",
    external: true,
    link: "https://chatgpt.com/g/g-dhkZ0P5ZL-ask-earth",
  },
  social_home_telegram: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "https://t.me/+MWUrdlbcUbE4MzA1",
  },
  social_home_twitter: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "https://twitter.com/solarpunkdao",
  },
  social_home_discord: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "https://discord.gg/67sjSmjd4m",
  },
  social_home_lens: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "",
  },
  social_home_farcaster: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "https://warpcast.com/earth-coin",
  },
  social_home_instagram: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "https://www.instagram.com/solarpunkdao.earth/",
  },
  social_home_linkedin: {
    position: "Join Us",
    page: "/",
    external: true,
    link: "https://www.linkedin.com/company/earth-solarpunkdao/",
  },
  earth_protocol_becomenode: {
    title: "Become a NODE",
    position: "Nodes",
    page: "/earth",
    external: false,
    link: "/earthnode",
  },
  earth_protocol_dapp: {
    title: "Go to DAPP",
    position: "Nodes",
    page: "/earth",
    external: false,
    link: "/dapp",
  },
  earth_uniswap_becomeNode: {
    title: "Go to Uniswap",
    position: "Nodes",
    page: "/earth",
    external: true,
    link: "https://app.uniswap.org/swap?inputCurrency=0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913&outputCurrency=0x9d6501275e91c0b2b0845C2c5334dEa1EC6a3c18",
  },
  footer_banner: {
    title: "Learn More",
    position: "Banner",
    page: "/",
    external: false,
    link: "/earthnode",
  },
  faq_footer_banner: {
    title: "Ask $Earth",
    position: "AI Banner",
    page: "/faq",
    external: true,
    link: "https://chatgpt.com/g/g-dhkZ0P5ZL-ask-earth",
  },
  projects_footer_banner: {
    title: "Ask $Earth",
    position: "AI Banner",
    page: "/projects",
    external: true,
    link: "https://chatgpt.com/g/g-dhkZ0P5ZL-ask-earth",
  },
  network_earthnode_bookslot: {
    title: "Book a slot",
    position: "Stepper",
    page: "/earthnode",
    external: true,
    link: "https://calendar.app.google/UgyzCz8bbga5rhed7",
  },
  network_earthnode_verified: {
    title: "Get KYC verified",
    position: "Stepper",
    page: "/earthnode",
    external: false,
    link: "/dapp?type=node",
  },
  network_earthnode_googleForm: {
    title: "Google Form",
    position: "Stepper",
    page: "/earthnode",
    external: true,
    link: "https://forms.gle/zx6Si4FTMKNUpBzH6",
  },
  network_earthnode_dapp: {
    title: "Go to DAPP",
    position: "Stepper",
    page: "/earthnode",
    external: false,
    link: "/dapp",
  },
  media_dexscreener:{
    title: "Dexscreener",
    position: "Dashboard",
    page: "/media",
    external: true,
    link: "https://dexscreener.com/polygon/0x40da612b7803892ed002e4f9effd746dc3cf4a5c",
  },
  media_get_started: {
    title: "Get $Earth",
    position: "Startups",
    page: "/media",
    external: false,
    link: "/dapp",
  },

};
