export const envObj = {
  personaTemplateId: process.env.NEXT_PUBLIC_PERSONA_TEMPLATE_ID,
  nexaflow_api_key: process.env.NEXT_PUBLIC_NEXAFLOW_API_KEY,
  nexaflow_api_url: process.env.NEXT_PUBLIC_NEXAFLOW_API_URL,
  ga_track_id: "",
  EarthTreasuryAddress: process.env.NEXT_PUBLIC_EARTHTREASURY_ADDRESS,
  presaleAddress: process.env.NEXT_PUBLIC_PRESALE_ADDRESS,
  soulboundAddress: process.env.NEXT_PUBLIC_SOULBOUND_CONTRACT_ADDRESS,
  claimAddress: process.env.NEXT_PUBLIC_CLAIM_CONTRACT_ADDRESS,
  stableCoinAddress: process.env.NEXT_PUBLIC_STABLE_COIN_ADDRESS,
  eartherc20Address: process.env.NEXT_PUBLIC_EARTH_ERC20_TOKEN_ADDRESS,
  fruitAddress: process.env.NEXT_PUBLIC_FRUIT_ADDRESS,
  earthstakingAddress: process.env.NEXT_PUBLIC_EARTH_STAKING_ADDRESS,
  chainId: process.env.NEXT_PUBLIC_CHAINID,
  network: process.env.NEXT_PUBLIC_NETWORK,
};
